@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model as ModelPackage <<Rectangle>>{
Class "<<interface>>\nReadOnlyTutorLink" as ReadOnlyTutorLink
Class "<<interface>>\nReadOnlyUserPrefs" as ReadOnlyUserPrefs
Class "<<interface>>\nModel" as Model
Class TutorLink
Class ModelManager
Class UserPrefs

Class UniqueStudentList
Class Student
Class Name
Class Subject
Class Interaction
Class FollowUp

Class I #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

TutorLink .up.|> ReadOnlyTutorLink

ModelManager .up.|> Model
Model .right.> ReadOnlyUserPrefs
Model .left.> ReadOnlyTutorLink
ModelManager -left-> "1" TutorLink
ModelManager -right-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

TutorLink *--> "1" UniqueStudentList
UniqueStudentList --> "~* all" Student
Student *--> "1" Name
Student *--> "*" Subject
Student *--> "*" Interaction
Student *--> "*" FollowUp

Student -[hidden]up--> I
UniqueStudentList -[hidden]right-> I

Name -[hidden]right-> Subject
Subject -[hidden]right-> Interaction
Interaction -[hidden]right-> FollowUp

ModelManager --> "~* filtered" Student
ModelManager --> "0..1 selected" Student
@enduml
